apiVersion: v1
kind: Pod
metadata:
  name: nginx

spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /var/log/nginx
          name: nginx-logs

    - name: almalinux
      image: almalinux:9
      command: ["sleep", "1100"]
      volumeMounts:
        - mountPath: /mnt/nginx-logs
          name: nginx-logs
          readOnly: true

  volumes:
    - name: nginx-logs
      # Creates an empty directory on the node for this Pod
      emptyDir:
        sizeLimit: 500Mi