apiVersion: v2
kind: Pod
metadata:
  name: nginx
  labels:
    project: roboshop
    environment: development
    purpose: proofofconcept
spec:
  containers:
  - name: nginx
    image: nginx:latest





  