apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: roboshop122
    environment: dev
    component: frontend
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx:latest