apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  # service labels
  labels:
    project: roboshop
    environment: dev
spec:
  type: NodePort
#service uses the below lables to select the pods

  selector:
    project: roboshop
    component: frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # cotainer port